# Generated by Django 4.1.2 on 2023-01-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdasapp', '0002_alter_complain_complainant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complainant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complainant_set', to='sdasapp.person'),
        ),
    ]
