# Generated by Django 4.1.2 on 2023-01-05 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdasapp', '0004_complain_incident_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='chair_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdasapp.person'),
        ),
    ]
