# Generated by Django 4.1.2 on 2023-01-05 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdasapp', '0005_alter_meeting_chair_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='chair_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chair_by_set', to='sdasapp.person'),
        ),
    ]
