# Generated by Django 4.1.2 on 2023-01-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdasapp', '0006_alter_meeting_chair_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='attendance_done',
            field=models.BooleanField(default=False),
        ),
    ]
