# Generated by Django 4.1.2 on 2023-01-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdasapp', '0007_complain_attendance_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='meetings',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='decisions',
        ),
        migrations.AddField(
            model_name='decision',
            name='meeting',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='sdasapp.meeting'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Meeting_Decision',
        ),
    ]
