# Generated by Django 4.1.2 on 2023-01-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdasapp', '0008_remove_decision_meetings_remove_meeting_decisions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='attendance_done',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='complain',
            name='complain_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='complain',
            name='meeting_assigned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
