# Generated by Django 4.1.2 on 2023-01-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdasapp', '0009_alter_complain_attendance_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('facultyMember', 'faculty Member'), ('Staff', 'Staff'), ('Student', 'Student')], max_length=20),
        ),
    ]
