# Generated by Django 4.1.2 on 2023-02-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdasapp', '0012_alter_person_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='comments',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
