# Generated by Django 4.1.2 on 2023-02-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdasapp', '0013_alter_staff_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_start_date',
            field=models.DateField(),
        ),
    ]
