# Generated by Django 4.1.2 on 2023-02-25 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdasapp', '0014_alter_term_term_end_date_alter_term_term_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.person'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.complain'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.meeting'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='headed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='headed_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complain',
            name='complainant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complainant_set', to='sdasapp.person'),
        ),
        migrations.AlterField(
            model_name='complain_committee',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.committee'),
        ),
        migrations.AlterField(
            model_name='complain_committee',
            name='complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.complain'),
        ),
        migrations.AlterField(
            model_name='complain_facultymember',
            name='Staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.facultymember'),
        ),
        migrations.AlterField(
            model_name='complain_facultymember',
            name='complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.complain'),
        ),
        migrations.AlterField(
            model_name='complain_meeting',
            name='complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.complain'),
        ),
        migrations.AlterField(
            model_name='complain_meeting',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sdasapp.meeting'),
        ),
        migrations.AlterField(
            model_name='complain_offence',
            name='complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.complain'),
        ),
        migrations.AlterField(
            model_name='complain_offence',
            name='offence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.offence'),
        ),
        migrations.AlterField(
            model_name='complain_staff',
            name='Staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.staff'),
        ),
        migrations.AlterField(
            model_name='complain_staff',
            name='complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.complain'),
        ),
        migrations.AlterField(
            model_name='complain_student',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.student'),
        ),
        migrations.AlterField(
            model_name='complain_student',
            name='complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.complain'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='complain',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='sdasapp.complain'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='meeting',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='sdasapp.meeting'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='offender_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.student'),
        ),
        migrations.AlterField(
            model_name='decision_penalty',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.decision'),
        ),
        migrations.AlterField(
            model_name='decision_penalty',
            name='penalty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='sdasapp.penalty'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.faculty'),
        ),
        migrations.AlterField(
            model_name='dept_facultymember',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.dept'),
        ),
        migrations.AlterField(
            model_name='dept_facultymember',
            name='faculty_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.facultymember'),
        ),
        migrations.AlterField(
            model_name='dept_staff',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.dept'),
        ),
        migrations.AlterField(
            model_name='dept_staff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.staff'),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.designation'),
        ),
        migrations.AlterField(
            model_name='facultymember_committee',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.committee'),
        ),
        migrations.AlterField(
            model_name='facultymember_committee',
            name='faculty_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.facultymember'),
        ),
        migrations.AlterField(
            model_name='facultymember_meeting',
            name='faculty_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.facultymember'),
        ),
        migrations.AlterField(
            model_name='facultymember_meeting',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='chair_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chair_by_set', to='sdasapp.person'),
        ),
        migrations.AlterField(
            model_name='program',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.dept'),
        ),
        migrations.AlterField(
            model_name='program',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.term'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.designation'),
        ),
        migrations.AlterField(
            model_name='staff_committee',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.committee'),
        ),
        migrations.AlterField(
            model_name='staff_committee',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.staff'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdasapp.term'),
        ),
    ]
