# Generated by Django 4.1.2 on 2023-03-21 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdasapp', '0015_alter_attendance_attendee_alter_attendance_complain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FYP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('image', models.ImageField(upload_to='fyp_images')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fyps', to='sdasapp.program')),
                ('students', models.ManyToManyField(related_name='fyp_students', to='sdasapp.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_fyps', to='sdasapp.facultymember')),
            ],
        ),
    ]
